blank_issues_enabled: true
contact_links:
  - name: How to Request Changes (Teachers)
    url: https://github.com/zkilianski/skills-expand-your-team-with-copilot/blob/main/docs/how-to-request-changes.md
    about: Learn how to use the issue templates to request changes
  - name: Development Guide
    url: https://github.com/zkilianski/skills-expand-your-team-with-copilot/blob/main/docs/how-to-develop.md
    about: Learn how to set up and develop the application
