blank_issues_enabled: true
contact_links:
  - name: Development Guide
    url: https://github.com/zkilianski/skills-expand-your-team-with-copilot/blob/main/docs/how-to-develop.md
    about: Learn how to set up and develop the application
